name: Pull Request Build

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Python
        run: |
          python -m venv ./venv --clear
          source ./venv/bin/activate
          pip install -r ./requirements.txt

      - name: Build docs
        run: |
          source ./venv/bin/activate
          chmod +x ./build.sh
          ./build.sh
      
      - name: Replace gallery images
        run: |
          sed -i -e "s/..\/img\/gallery\//https:\/\/raw.githubusercontent.com\/chunky-dev\/docs\/$GITHUB_SHA\/ChunkyDocs\/docs\/img\/gallery\//g" ./docs/gallery/index.html
          rm -rf ./docs/img/gallery/

      - name: Save PR Number
        run: echo ${{ github.event.number }} > ./docs/pr-number.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: site
          path: ./docs/
          if-no-files-found: error
